# Generated by Django 2.2.7 on 2019-11-26 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('remark', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GraphConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noun', models.BooleanField(default=False)),
                ('pronoun', models.BooleanField(default=False)),
                ('adjective', models.BooleanField(default=False)),
                ('window', models.IntegerField(default=1)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='core.File')),
            ],
        ),
    ]
